### ISSUE TITLE
Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1364 Field 's3url' doesn't have a default value in 

### ISSUE THREAD

**Issue by siramsay** [chishiki/perihelion#35]
`Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1364 Field 's3url' doesn't have a default value in /Users/rambo/Sites/github/p2/deploy/src/perihelion/php/model/orm.model.php:24 Stack trace: #0 /Users/rambo/Sites/github/p2/deploy/src/perihelion/php/model/orm.model.php(24): PDOStatement->execute() #1 /Users/rambo/Sites/github/p2/deploy/src/perihelion/php/model/file.model.php(191): ORM::insert(Object(File)) #2 /Users/rambo/Sites/github/p2/deploy/src/perihelion/php/controller/designer.controller.php(252): File::uploadFiles(Array, 'Site', '110', 'Good Enough', '\xE3\x83\x86\xE3\x82\xB9\xE3\x83\x88') #3 /Users/rambo/Sites/github/p2/deploy/src/perihelion/php/controller/_state.controller.php(50): DesignerController->setState() #4 /Users/rambo/Sites/github/p2/deploy/src/perihelion/php/controller/_perihelion.controller.php(303): StateController->setState() #5 /Users/rambo/Sites/github/p2/deploy/src/index.php(5): Controller->orbit() #6 {main} thrown in /Users/rambo/Sites/github/p2/deploy/src/perihelion/php/model/orm.model.php on line 24`

s3url doesn't have a default value that can be temporarily fixed by adding it to the new File object in file.model.php before line 190.

```
$file->fileTitleJapanese = $fileNameJapanese;
+ $file->s3url = "";
```

**Comment by siramsay** [comment]
There are other issues with the file upload page, more to do with UI/UX, and also had issue with the upload size, Will open another issue with recommended tweaks.

**Comment by siramsay** [comment]
Just started a new issue for other File Upload functionality as this is an SQL issue and the #42 are script issues.
